#!/usr/bin/env python3
"""
Paper Trading Tracker for NSE AlphaBot
Tracks signals, simulates trades, and validates performance
"""

import json
import os
from datetime import datetime
import pandas as pd
import yfinance as yf

# Configuration
PAPER_TRADING_LOG = "paper_trading_log.json"
PERFORMANCE_REPORT = "paper_trading_performance.csv"
INITIAL_CAPITAL = 500000
RISK_PER_TRADE = 0.03

class PaperTradingTracker:
    """Track paper trading performance"""
    
    def __init__(self):
        self.log_file = PAPER_TRADING_LOG
        self.performance_file = PERFORMANCE_REPORT
        self.load_log()
    
    def load_log(self):
        """Load existing paper trading log"""
        if os.path.exists(self.log_file):
            with open(self.log_file, 'r') as f:
                self.log = json.load(f)
        else:
            self.log = {
                'start_date': datetime.now().strftime('%Y-%m-%d'),
                'initial_capital': INITIAL_CAPITAL,
                'current_capital': INITIAL_CAPITAL,
                'trades': [],
                'daily_signals': []
            }
    
    def save_log(self):
        """Save paper trading log"""
        with open(self.log_file, 'w') as f:
            json.dump(self.log, f, indent=2)
    
    def log_daily_signals(self, signals):
        """
        Log signals generated by the bot
        
        Args:
            signals: List of signal dicts from bot
        """
        date = datetime.now().strftime('%Y-%m-%d')
        time = datetime.now().strftime('%H:%M:%S')
        
        daily_entry = {
            'date': date,
            'time': time,
            'num_signals': len(signals),
            'signals': []
        }
        
        for signal in signals:
            signal_entry = {
                'ticker': signal['ticker'],
                'price': signal['price'],
                'confidence': signal['confidence'],
                'expected_return': signal['expected_return'],
                'mtf_score': signal['mtf_score'],
                'smc_score': signal['smc_score'],
                'tech_score': signal['tech_score'],
                'sentiment_score': signal['sentiment_score'],
                'ai_score': signal.get('ai_score', 0.5),
                'shares': signal.get('shares', 0),
                'capital_allocated': signal.get('capital_allocated', 0)
            }
            daily_entry['signals'].append(signal_entry)
        
        self.log['daily_signals'].append(daily_entry)
        self.save_log()
        
        print(f"\n✅ Logged {len(signals)} signals for {date}")
    
    def execute_paper_trade(self, ticker, entry_price, shares, stop_loss_pct=0.05):
        """
        Execute a paper trade
        
        Args:
            ticker: Stock ticker
            entry_price: Entry price
            shares: Number of shares
            stop_loss_pct: Stop loss percentage (default 5%)
        """
        trade = {
            'trade_id': len(self.log['trades']) + 1,
            'ticker': ticker,
            'entry_date': datetime.now().strftime('%Y-%m-%d'),
            'entry_time': datetime.now().strftime('%H:%M:%S'),
            'entry_price': entry_price,
            'shares': shares,
            'capital_invested': entry_price * shares,
            'stop_loss': entry_price * (1 - stop_loss_pct),
            'target': None,  # Will be set based on expected return
            'status': 'OPEN',
            'exit_date': None,
            'exit_price': None,
            'pnl': None,
            'pnl_pct': None,
            'days_held': None
        }
        
        self.log['trades'].append(trade)
        self.save_log()
        
        print(f"\n📝 Paper Trade Executed:")
        print(f"   Ticker: {ticker}")
        print(f"   Entry: ₹{entry_price:.2f}")
        print(f"   Shares: {shares}")
        print(f"   Capital: ₹{trade['capital_invested']:,.0f}")
        print(f"   Stop Loss: ₹{trade['stop_loss']:.2f}")
    
    def update_open_trades(self):
        """Update status of all open trades"""
        print("\n🔄 Updating open trades...")
        
        for trade in self.log['trades']:
            if trade['status'] == 'OPEN':
                ticker = trade['ticker']
                
                try:
                    # Get current price
                    stock = yf.Ticker(ticker)
                    current_price = stock.history(period='1d')['Close'].iloc[-1]
                    
                    # Calculate current P&L
                    entry_price = trade['entry_price']
                    shares = trade['shares']
                    current_value = current_price * shares
                    invested = trade['capital_invested']
                    pnl = current_value - invested
                    pnl_pct = (pnl / invested) * 100
                    
                    # Calculate days held
                    entry_date = datetime.strptime(trade['entry_date'], '%Y-%m-%d')
                    days_held = (datetime.now() - entry_date).days
                    
                    print(f"\n   {ticker}:")
                    print(f"   Entry: ₹{entry_price:.2f} → Current: ₹{current_price:.2f}")
                    print(f"   P&L: ₹{pnl:,.0f} ({pnl_pct:+.2f}%)")
                    print(f"   Days: {days_held}")
                    
                    # Check stop loss
                    if current_price <= trade['stop_loss']:
                        self.close_trade(trade['trade_id'], current_price, 'STOP_LOSS')
                        print(f"   ⚠️  STOP LOSS HIT!")
                    
                except Exception as e:
                    print(f"   ❌ Error updating {ticker}: {str(e)[:50]}")
        
        self.save_log()
    
    def close_trade(self, trade_id, exit_price, reason='MANUAL'):
        """
        Close a paper trade
        
        Args:
            trade_id: Trade ID
            exit_price: Exit price
            reason: Reason for closing (MANUAL, STOP_LOSS, TARGET, etc.)
        """
        for trade in self.log['trades']:
            if trade['trade_id'] == trade_id and trade['status'] == 'OPEN':
                # Calculate P&L
                entry_price = trade['entry_price']
                shares = trade['shares']
                invested = trade['capital_invested']
                exit_value = exit_price * shares
                pnl = exit_value - invested
                pnl_pct = (pnl / invested) * 100
                
                # Calculate days held
                entry_date = datetime.strptime(trade['entry_date'], '%Y-%m-%d')
                days_held = (datetime.now() - entry_date).days
                
                # Update trade
                trade['status'] = 'CLOSED'
                trade['exit_date'] = datetime.now().strftime('%Y-%m-%d')
                trade['exit_time'] = datetime.now().strftime('%H:%M:%S')
                trade['exit_price'] = exit_price
                trade['pnl'] = pnl
                trade['pnl_pct'] = pnl_pct
                trade['days_held'] = days_held
                trade['close_reason'] = reason
                
                # Update capital
                self.log['current_capital'] += pnl
                
                self.save_log()
                
                print(f"\n✅ Trade Closed:")
                print(f"   Ticker: {trade['ticker']}")
                print(f"   Entry: ₹{entry_price:.2f} → Exit: ₹{exit_price:.2f}")
                print(f"   P&L: ₹{pnl:,.0f} ({pnl_pct:+.2f}%)")
                print(f"   Days: {days_held}")
                print(f"   Reason: {reason}")
                
                return True
        
        print(f"❌ Trade {trade_id} not found or already closed")
        return False
    
    def generate_performance_report(self):
        """Generate comprehensive performance report"""
        print("\n" + "="*100)
        print("📊 PAPER TRADING PERFORMANCE REPORT")
        print("="*100)
        
        # Overall stats
        start_date = self.log['start_date']
        initial_capital = self.log['initial_capital']
        current_capital = self.log['current_capital']
        total_pnl = current_capital - initial_capital
        total_pnl_pct = (total_pnl / initial_capital) * 100
        
        print(f"\n📅 Period: {start_date} to {datetime.now().strftime('%Y-%m-%d')}")
        print(f"💰 Initial Capital: ₹{initial_capital:,.0f}")
        print(f"💰 Current Capital: ₹{current_capital:,.0f}")
        print(f"📈 Total P&L: ₹{total_pnl:,.0f} ({total_pnl_pct:+.2f}%)")
        
        # Trade statistics
        closed_trades = [t for t in self.log['trades'] if t['status'] == 'CLOSED']
        open_trades = [t for t in self.log['trades'] if t['status'] == 'OPEN']
        
        print(f"\n📊 Trade Statistics:")
        print(f"   Total Trades: {len(self.log['trades'])}")
        print(f"   Closed: {len(closed_trades)}")
        print(f"   Open: {len(open_trades)}")
        
        if closed_trades:
            # Win rate
            winning_trades = [t for t in closed_trades if t['pnl'] > 0]
            losing_trades = [t for t in closed_trades if t['pnl'] <= 0]
            win_rate = (len(winning_trades) / len(closed_trades)) * 100
            
            # Average returns
            avg_win = sum(t['pnl_pct'] for t in winning_trades) / len(winning_trades) if winning_trades else 0
            avg_loss = sum(t['pnl_pct'] for t in losing_trades) / len(losing_trades) if losing_trades else 0
            avg_return = sum(t['pnl_pct'] for t in closed_trades) / len(closed_trades)
            
            # Risk-reward
            risk_reward = abs(avg_win / avg_loss) if avg_loss != 0 else 0
            
            # Average holding period
            avg_days = sum(t['days_held'] for t in closed_trades) / len(closed_trades)
            
            print(f"\n📈 Performance Metrics:")
            print(f"   Win Rate: {win_rate:.1f}% ({len(winning_trades)}/{len(closed_trades)})")
            print(f"   Average Win: +{avg_win:.2f}%")
            print(f"   Average Loss: {avg_loss:.2f}%")
            print(f"   Average Return: {avg_return:+.2f}%")
            print(f"   Risk-Reward Ratio: {risk_reward:.2f}:1")
            print(f"   Average Holding: {avg_days:.1f} days")
            
            # Best and worst trades
            best_trade = max(closed_trades, key=lambda t: t['pnl_pct'])
            worst_trade = min(closed_trades, key=lambda t: t['pnl_pct'])
            
            print(f"\n🏆 Best Trade:")
            print(f"   {best_trade['ticker']}: {best_trade['pnl_pct']:+.2f}% (₹{best_trade['pnl']:,.0f})")
            
            print(f"\n📉 Worst Trade:")
            print(f"   {worst_trade['ticker']}: {worst_trade['pnl_pct']:+.2f}% (₹{worst_trade['pnl']:,.0f})")
        
        # Signal statistics
        total_signals = sum(day['num_signals'] for day in self.log['daily_signals'])
        avg_signals_per_day = total_signals / len(self.log['daily_signals']) if self.log['daily_signals'] else 0
        
        print(f"\n📡 Signal Statistics:")
        print(f"   Total Days: {len(self.log['daily_signals'])}")
        print(f"   Total Signals: {total_signals}")
        print(f"   Avg Signals/Day: {avg_signals_per_day:.1f}")
        
        # Export to CSV
        if closed_trades:
            df = pd.DataFrame(closed_trades)
            df.to_csv(self.performance_file, index=False)
            print(f"\n💾 Performance data exported to: {self.performance_file}")
        
        print("="*100)
    
    def show_open_positions(self):
        """Show all open positions"""
        open_trades = [t for t in self.log['trades'] if t['status'] == 'OPEN']
        
        if not open_trades:
            print("\n📭 No open positions")
            return
        
        print("\n" + "="*100)
        print("📊 OPEN POSITIONS")
        print("="*100)
        print(f"{'Ticker':<15} {'Entry':>10} {'Current':>10} {'P&L':>12} {'P&L%':>8} {'Days':>5} {'Stop':>10}")
        print("-"*100)
        
        total_invested = 0
        total_current = 0
        
        for trade in open_trades:
            ticker = trade['ticker']
            
            try:
                # Get current price
                stock = yf.Ticker(ticker)
                current_price = stock.history(period='1d')['Close'].iloc[-1]
                
                entry_price = trade['entry_price']
                shares = trade['shares']
                invested = trade['capital_invested']
                current_value = current_price * shares
                pnl = current_value - invested
                pnl_pct = (pnl / invested) * 100
                
                entry_date = datetime.strptime(trade['entry_date'], '%Y-%m-%d')
                days_held = (datetime.now() - entry_date).days
                
                total_invested += invested
                total_current += current_value
                
                print(f"{ticker:<15} ₹{entry_price:>9.2f} ₹{current_price:>9.2f} "
                      f"₹{pnl:>10,.0f} {pnl_pct:>7.2f}% {days_held:>5} ₹{trade['stop_loss']:>9.2f}")
                
            except Exception as e:
                print(f"{ticker:<15} Error fetching price")
        
        print("-"*100)
        total_pnl = total_current - total_invested
        total_pnl_pct = (total_pnl / total_invested) * 100 if total_invested > 0 else 0
        print(f"{'TOTAL':<15} ₹{total_invested:>9,.0f} ₹{total_current:>9,.0f} "
              f"₹{total_pnl:>10,.0f} {total_pnl_pct:>7.2f}%")
        print("="*100)


def main():
    """Main function for paper trading tracker"""
    import sys
    
    tracker = PaperTradingTracker()
    
    if len(sys.argv) < 2:
        print("\n📊 NSE AlphaBot - Paper Trading Tracker")
        print("\nUsage:")
        print("  python3 paper_trading_tracker.py log <signals.json>    # Log daily signals")
        print("  python3 paper_trading_tracker.py trade <ticker> <price> <shares>  # Execute paper trade")
        print("  python3 paper_trading_tracker.py update               # Update open trades")
        print("  python3 paper_trading_tracker.py close <trade_id> <exit_price>  # Close trade")
        print("  python3 paper_trading_tracker.py report               # Generate performance report")
        print("  python3 paper_trading_tracker.py positions            # Show open positions")
        return
    
    command = sys.argv[1]
    
    if command == 'log':
        # Log signals from file
        if len(sys.argv) < 3:
            print("❌ Usage: python3 paper_trading_tracker.py log <signals.json>")
            return
        
        with open(sys.argv[2], 'r') as f:
            signals = json.load(f)
        
        tracker.log_daily_signals(signals)
    
    elif command == 'trade':
        # Execute paper trade
        if len(sys.argv) < 5:
            print("❌ Usage: python3 paper_trading_tracker.py trade <ticker> <price> <shares>")
            return
        
        ticker = sys.argv[2]
        price = float(sys.argv[3])
        shares = int(sys.argv[4])
        
        tracker.execute_paper_trade(ticker, price, shares)
    
    elif command == 'update':
        # Update open trades
        tracker.update_open_trades()
    
    elif command == 'close':
        # Close trade
        if len(sys.argv) < 4:
            print("❌ Usage: python3 paper_trading_tracker.py close <trade_id> <exit_price>")
            return
        
        trade_id = int(sys.argv[2])
        exit_price = float(sys.argv[3])
        
        tracker.close_trade(trade_id, exit_price, 'MANUAL')
    
    elif command == 'report':
        # Generate performance report
        tracker.generate_performance_report()
    
    elif command == 'positions':
        # Show open positions
        tracker.show_open_positions()
    
    else:
        print(f"❌ Unknown command: {command}")


if __name__ == "__main__":
    main()
